### ISSUE TITLE
公众号抓取问题

### ISSUE THREAD

**Issue by airyyan** [TeamWiseFlow/awada#5]
手机上微信账号退出时，windows客户端的微信也会被强制退出，所以wxbot是不是也一样？我需要每次重启wxbot和awada才能抓取公众号信息，否则就一直都没抓取

**Comment by bigbrother666sh** [comment]
如果显示的windows登录也被退出了，那是的

**Comment by airyyan** [comment]
![image](https://github.com/user-attachments/assets/c9b9d568-b1f5-4fcc-a8cf-76c6241e0095)
awada时间久了就会断掉，不监听wxbot了，每天需要重启awada才行，这个怎么解决

**Comment by bigbrother666sh** [comment]
你用的是最新repo里面的dm.py吗？
另外你的环境是什么？
最后你这个微信接收消息多不多？长时间没有消息进来是容易断
